### ISSUE TITLE
Resolvers

### ISSUE THREAD

**Issue by motiejunas** [Wufe/mapper#1]
Is there any plans for adding resolvers?

I want to be able to use them like in AutoMapper:
opt => opt.ResolveUsing(new TestQuestionsCountResolver(testService))

**Comment by wufe** [comment]
I'll work on it as soon as possible

**Comment by wufe** [comment]
@motiejunas 
I noticed that the projection operation works as a custom value resolver.
Check [this](https://github.com/Wufe/mapper/blob/17b5fe8ad66afc2b4ee5ffa7e6281b4551878a54/src/tests/mapper.test.ts#L492) example in the tests file.

Let me know if you have doubts.

**Comment by motiejunas** [comment]
@Wufe exactly what I was looking for
