### ISSUE TITLE
mapper does not work as expected

### ISSUE THREAD

**Issue by motiejunas** [Wufe/mapper#4]
`
import { Mapper, mapTo } from '@wufe/mapper';

class UserDto {
  id: number;
  username: string;
}

@mapTo(UserDto)
class User {
  id: number;
  username: string;
  password: string;
}

const mapper = new Mapper();
mapper.createMap<User, UserDto>(User);

const user = new User();
user.id = 1;
user.username = 'test-user';
user.password = '123';

const userDto = mapper.map<User, UserDto>(user);

console.log(userDto); // prints out - { id: 1, username: 'test-user', password: '123' }
`

My expectations: mapper should ignore not existing properties (by default) as AutoMapper does.

Why password field still exists in userDto? Did I miss something?

**Comment by wufe** [comment]
A class definition does not contain any object: *i.e.* UserDto object has no properties in it.  
The mapper cannot tell which properties the destination already has. It is a javascript limitation.  
You may want to ignore the unwanted property instead with [opt.ignore()](https://github.com/Wufe/mapper/wiki/Operation-configuration#ignore)

UPDATE:
Try also [shouldIgnoreSourcePropertiesIfNotInDestination(true)](https://github.com/Wufe/mapper/wiki/Mapper-configuration#ignore-source-properties-if-not-in-destination)

**Comment by wufe** [comment]
Closing for stale.
